version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.2.0

workflows:
  deploy:
    jobs:
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: tetsuya28/gcp-oidc-public
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
